# Imagem base oficial do PHP com Apache
FROM php:8.2-apache

# Ativa o mod_rewrite (opcional, mas útil se usar rotas)
RUN a2enmod rewrite

# Instalar a extensão mysqli
RUN docker-php-ext-install mysqli

# Instalar o Composer
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    curl 
    
# Instale o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copia os arquivos do backend para o Apache
COPY . /var/www/html/

# Ajusta permissões 
RUN chown -R www-data:www-data /var/www/html

# Expõe a porta 80 (usada pelo Apache)
EXPOSE 80
